global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flask_app"
    static_configs:
      - targets: ["13.203.216.233:5000"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["13.203.216.233:9100"]